# Uncomment the next line to define a global platform for your project
 platform :ios, '12.2'

target 'ProductSearch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProductSearch
  pod 'Alamofire', '~> 5.0.0-beta.4'
  pod "SwiftyJSON"
  pod "McPicker"
  pod "SwiftSpinner"
  pod "Toast-Swift"
end
